import pygame

sprites: dict = {
    'player_nr': pygame.image.load(r"image/player/player_nr.png"),
    'player_pd': pygame.image.load(r"image/player/player_pd.png"),
    'hat': pygame.image.load(r"image/player/hat.png"),
    'default_projectile': None,
    'projectile30': pygame.image.load(r"image/projectiles/projectile30.png"),
    'grass1': pygame.image.load(r"image/grasses/grass1.png"),
    'grass2': pygame.image.load(r"image/grasses/grass2.png"),
    'grass3': pygame.image.load(r"image/grasses/grass3.png"),
    'grass4': pygame.image.load(r"image/grasses/grass4.png"),
    'grass5': pygame.image.load(r"image/grasses/grass5.png"),
    'stone1': pygame.image.load(r"image/stones/stone1.png"),
    'cursor': pygame.image.load(r"image/cursor.png"),
    'texture_grass_0': pygame.image.load(r"image/texture_grass/texture_grass_0.png"),
    'texture_grass_1': pygame.image.load(r"image/texture_grass/texture_grass_1.png"),
    'texture_grass_2': pygame.image.load(r"image/texture_grass/texture_grass_2.png"),
    'texture_grass_3': pygame.image.load(r"image/texture_grass/texture_grass_3.png"),
    'texture_grass_4': pygame.image.load(r"image/texture_grass/texture_grass_4.png"),
    'texture_grass_5': pygame.image.load(r"image/texture_grass/texture_grass_5.png"),
    'texture_grass_6': pygame.image.load(r"image/texture_grass/texture_grass_6.png"),
    'texture_grass_7': pygame.image.load(r"image/texture_grass/texture_grass_7.png"),
    'texture_grass_8': pygame.image.load(r"image/texture_grass/texture_grass_8.png"),
}
